# Generated by Django 4.1.3 on 2022-11-16 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0002_remove_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=264)),
                ('full_name', models.CharField(blank=True, max_length=264)),
                ('address1', models.TextField(blank=True, max_length=300)),
                ('zipCode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('JoinedDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profileRelatedName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
