# Generated by Django 4.1.3 on 2022-11-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0005_user_phone_number_user_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
