# Generated by Django 4.1.3 on 2022-11-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_password_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
