# Generated by Django 4.1.3 on 2022-11-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0007_user_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
