# Generated by Django 4.1.3 on 2022-11-19 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0011_remove_user_forget_password_token_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profileRelatedName', to=settings.AUTH_USER_MODEL),
        ),
    ]
