# Generated by Django 4.1.3 on 2022-11-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0014_foodcategories_foodmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmenu',
            name='Category',
        ),
        migrations.DeleteModel(
            name='FoodCategories',
        ),
        migrations.DeleteModel(
            name='FoodMenu',
        ),
    ]
