# Generated by Django 4.1.3 on 2022-11-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0016_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
