# Generated by Django 4.1.3 on 2022-11-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDeliveryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='0_DynamicImages/Food_Image'),
        ),
    ]
