# Generated by Django 4.1.3 on 2022-11-23 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodDeliveryApp', '0002_foodmenu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemPrice', models.CharField(blank=True, max_length=264, null=True)),
                ('quantity', models.CharField(blank=True, max_length=264, null=True)),
                ('totalPrice', models.CharField(blank=True, max_length=264, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('post_office', models.CharField(blank=True, max_length=250, null=True)),
                ('thana', models.CharField(blank=True, max_length=250, null=True)),
                ('district', models.CharField(blank=True, max_length=250, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=264, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PurchasedItemRelatedName', to='foodDeliveryApp.foodmenu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PurchasedItemUserRelatedName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
