# Generated by Django 4.1.3 on 2022-11-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDeliveryApp', '0003_purchaseditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditem',
            name='user',
        ),
    ]
