# Generated by Django 4.1.3 on 2022-11-23 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodDeliveryApp', '0004_remove_purchaseditem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchasedItemUserRelatedName', to=settings.AUTH_USER_MODEL),
        ),
    ]
