# Generated by Django 4.1.3 on 2022-11-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDeliveryApp', '0005_purchaseditem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='customerName',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
