# Generated by Django 4.1.3 on 2022-11-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDeliveryApp', '0006_purchaseditem_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='transactionId',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='purchaseditem',
            name='validationID',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
