# Generated by Django 4.1.3 on 2022-11-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDeliveryApp', '0007_purchaseditem_transactionid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='OrderStatus',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], max_length=30, null=True),
        ),
    ]
