# Generated by Django 4.1.3 on 2022-11-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDeliveryApp', '0008_purchaseditem_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategories',
            name='CategoryName',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
